<a href="https://colab.research.google.com/github/Marvsr05/SC-Sesi-1/blob/main/SC_sesi_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print ("hello")

hello


In [ ]:
import time

In [ ]:
print(time.ctime())

Fri Feb  7 12:39:30 2025


In [ ]:
z = "Hello"
y = 20
c = 30.9
f = ["Apple", "berry"]

z,y,c,f
print (z,y,c,f)

Hello 20 30.9 ['Apple', 'berry']


In [ ]:
o = int(1)
y = int(2.8)
z = int("3")
j = str(20)
print(o,y,z,j)

1 2 3 20


In [ ]:
a = "Hello"
b = " world"
c = a+b

print(c)

Hello world


In [ ]:
a = "Hello world"
print(a[1])

print(len(a))

e
11


In [ ]:
b = "BINUS Univ"
print(b[2:5])

c = "BINUS Univ"
print(c[:5])

d = "BINUS Univ"
print(d[2:])

NUS
BINUS
NUS Univ


In [ ]:
a = "Hello"
print(a.upper())

b = "Hello"
print(b.lower())

c = "Hello"
print(a.replace("H", "J"))

HELLO
hello
Jello


In [ ]:
nama = "Marv"
x = 18
string = "nama saya {} umur {}"

print(string.format(nama, x))

nama saya Marv umur 18


In [ ]:
nama = "Grace"
for i in enumerate(nama):
    print(i)

(0, 'G')
(1, 'r')
(2, 'a')
(3, 'c')
(4, 'e')


In [ ]:
def perbandingan (a,b):
  if a > b:
    print("a lebih dari b")
  elif a<b:
   print("a kurang dari b")
  else:
    print("a = b")


In [ ]:
perbandingan(4,8)

a kurang dari b


In [ ]:
i = 1
while i<6:
  print(i)
  i += 1

1
2
3
4
5


In [ ]:
i=3
for i in range(0,6):
  print(i)

0
1
2
3
4
5


In [ ]:
i = 1
for i in range(2,40):
  if i % 2 == 1:
   print(i, "ganjil")

  elif i % 2 == 0:
   print(i, "genap")

2 genap
3 ganjil
4 genap
5 ganjil
6 genap
7 ganjil
8 genap
9 ganjil
10 genap
11 ganjil
12 genap
13 ganjil
14 genap
15 ganjil
16 genap
17 ganjil
18 genap
19 ganjil
20 genap
21 ganjil
22 genap
23 ganjil
24 genap
25 ganjil
26 genap
27 ganjil
28 genap
29 ganjil
30 genap
31 ganjil
32 genap
33 ganjil
34 genap
35 ganjil
36 genap
37 ganjil
38 genap
39 ganjil


In [ ]:
import numpy as np

In [ ]:
x = np.array([[1,2,3], [3,6,7]])
x

array([[1, 2, 3],
       [3, 6, 7]])

In [ ]:
y = np.array([[8,2,9], [3,5,7]])
y

array([[8, 2, 9],
       [3, 5, 7]])

In [ ]:
print(x+y)

[[ 9  4 12]
 [ 6 11 14]]


In [ ]:
data = np.array([10,9,8,7,5,6])
print("Rata-Rata:", np.mean(data))
print("Maksimum:", np.max(data))
print("Minimum:", np.min(data))
print("Standar Deviasi:", np.std(data))

Rata-Rata: 7.5
Maksimum: 10
Minimum: 5
Standar Deviasi: 1.707825127659933


In [ ]:
def valid_input(prompt):
    while True:
        try:
            value = float(input(prompt))
            if 0 <= value <= 100:
                return value
            else:
                print("Nilai harus antara 0 dan 100.")
        except ValueError:
            print("Input tidak valid, harap masukkan angka.")

def login():
    username = input("Masukkan username anda: ")
    pswd = input("Masukkan password anda: ")
    while pswd != "Admin123":
        print("Username atau password salah. Silakan coba lagi.")
        pswd = input("Masukkan password anda: ")
    print(f"Login berhasil! Selamat datang, {username}.")

def calculate(UAS, UTS, ASG):
  return (0.5 * UAS) + (0.3 * UTS) + (0.2 * ASG)

def grade(nilai):
  if nilai >= 90:
    return "A"
  elif nilai >= 85:
    return "A-"
  elif nilai >= 80:
    return "B+"
  elif nilai >= 75:
    return "B"
  elif nilai >= 70:
    return "B-"
  elif nilai >= 65:
    return "C"
  elif nilai >= 60:
    return "D"
  elif nilai >= 11:
    return "E"
  else:
    return "F"

def main():
  login()
  username = input("Masukkan nama mahasiswa: ")

  UAS = valid_input("Masukkan nilai UAS: ")
  UTS = valid_input("Masukkan nilai UTS: ")
  ASG = valid_input("Masukkan nilai Assignment: ")
  nilai = calculate(UAS, UTS, ASG)
  final_grade = grade(nilai)
  print("======================================1=\n")
  print(f"Hasil perolehan nilai {username}")
  print(f"Final Score: {nilai:.2f}")
  print(f"Grade: {final_grade}")
  print("\n======================================")

if __name__ == "__main__":
  main()

Masukkan username anda: halo
Masukkan password anda: admin
Username atau password salah. Silakan coba lagi.
Masukkan password anda: Admin123
Login berhasil! Selamat datang, halo.
Masukkan nama mahasiswa: Marvel S
Masukkan nilai UAS: 88
Masukkan nilai UTS: 92
Masukkan nilai Assignment: 98
======================================1=

Hasil perolehan nilai Marvel S
Final Score: 91.20
Grade: A

